[theme]
primaryColor = "#FCA70A"
backgroundColor = "#CC5703"
secondaryBackgroundColor = "#D4D1CB"
textColor = "#929EA0"

# Puedes ajustar estos valores seg√∫n prefieras
# primaryColor: para botones y acentos
# backgroundColor: fondo principal (anaranjado)
# secondaryBackgroundColor: fondo de paneles/sidebars
# textColor: color del texto
